// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using catalog_service.Data;

#nullable disable

namespace catalog_service.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    [Migration("20260705182743_AddCropsTable")]
    partial class AddCropsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("catalog_service.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedByAdminId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("ManagedByStaffId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Phân bón và hóa chất"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Thuốc trừ bệnh"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Thuốc trừ cỏ"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Thuốc trừ sâu"
                        });
                });

            modelBuilder.Entity("catalog_service.Models.Crop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Crops");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Cây lương thực chính yếu, dễ gặp sâu đục thân, rầy nâu, đạo ôn.",
                            ImageUrl = "https://images.unsplash.com/photo-1590682680695-43b964a3ae17?q=80&w=600&auto=format&fit=crop",
                            IsActive = true,
                            Name = "Lúa (Rice)",
                            Slug = "lua"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Cây xoài, sầu riêng, cam bưởi... Cần nhiều vi lượng để nuôi trái, ra hoa.",
                            ImageUrl = "https://images.unsplash.com/photo-1595163155799-1bd12028ab67?q=80&w=600&auto=format&fit=crop",
                            IsActive = true,
                            Name = "Cây Ăn Trái",
                            Slug = "cay-an-trai"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Rau ăn lá, họ dưa bầu bí... dễ gặp sâu tơ, bọ trĩ, phấn trắng.",
                            ImageUrl = "https://images.unsplash.com/photo-1506484381205-f7945653044d?q=80&w=600&auto=format&fit=crop",
                            IsActive = true,
                            Name = "Rau Màu",
                            Slug = "rau-mau"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Cà phê, hồ tiêu, cao su, điều... Các loại cây có giá trị kinh tế cao, cần quản lý nấm bệnh, rệp sáp rễ.",
                            ImageUrl = "https://images.unsplash.com/photo-1611162458324-aae1eb4129a4?q=80&w=600&auto=format&fit=crop",
                            IsActive = true,
                            Name = "Cây Công Nghiệp",
                            Slug = "cay-cong-nghiep"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Khoai lang, sắn, khoai tây, cà rốt... Cần thuốc trừ tuyến trùng rễ và nhện đỏ.",
                            ImageUrl = "https://images.unsplash.com/photo-1593005872758-00ee9c1e7ea0?q=80&w=600&auto=format&fit=crop",
                            IsActive = true,
                            Name = "Cây Lấy Củ",
                            Slug = "cay-lay-cu"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Hoa hồng, lan, cúc... Dễ mắc bệnh rỉ sắt, đốm lá và nhện đỏ.",
                            ImageUrl = "https://images.unsplash.com/photo-1490750967868-88cb4ecb07fa?q=80&w=600&auto=format&fit=crop",
                            IsActive = true,
                            Name = "Hoa và Cây Cảnh",
                            Slug = "hoa-cay-canh"
                        });
                });

            modelBuilder.Entity("catalog_service.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int?>("ChemicalProfileId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedByAdminId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("ManagedByStaffId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SKU")
                        .IsUnique();

                    b.ToTable("Products");
                });

            modelBuilder.Entity("catalog_service.Models.ProductCrop", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("CropId")
                        .HasColumnType("int");

                    b.Property<string>("UsageInstruction")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("ProductId", "CropId");

                    b.HasIndex("CropId");

                    b.ToTable("ProductCrops");

                    b.HasData(
                        new
                        {
                            ProductId = 50,
                            CropId = 1,
                            UsageInstruction = "Đặc trị rầy nâu, sâu đục thân hại lúa."
                        },
                        new
                        {
                            ProductId = 47,
                            CropId = 1,
                            UsageInstruction = "Đặc trị bệnh đạo ôn trên lúa."
                        },
                        new
                        {
                            ProductId = 3,
                            CropId = 1,
                            UsageInstruction = "Trừ ốc bươu vàng hại lúa non."
                        },
                        new
                        {
                            ProductId = 8,
                            CropId = 1,
                            UsageInstruction = "Giữ xanh lá đòng, hạt lúa sáng mẩy."
                        },
                        new
                        {
                            ProductId = 1,
                            CropId = 2,
                            UsageInstruction = "Cung cấp Bo và Kẽm giúp đậu trái, chống rụng hoa."
                        },
                        new
                        {
                            ProductId = 4,
                            CropId = 2,
                            UsageInstruction = "Kích thích ra hoa sớm, đồng loạt."
                        },
                        new
                        {
                            ProductId = 22,
                            CropId = 2,
                            UsageInstruction = "Cung cấp dinh dưỡng NPK nuôi trái lớn."
                        },
                        new
                        {
                            ProductId = 60,
                            CropId = 2,
                            UsageInstruction = "Phòng trị bệnh thán thư sầu riêng, nứt thân xì mủ."
                        },
                        new
                        {
                            ProductId = 2,
                            CropId = 3,
                            UsageInstruction = "Thuốc sinh học an toàn trừ sâu tơ bắp cải."
                        },
                        new
                        {
                            ProductId = 78,
                            CropId = 3,
                            UsageInstruction = "Đặc trị bệnh phấn trắng trên dưa leo, bầu bí."
                        },
                        new
                        {
                            ProductId = 9,
                            CropId = 3,
                            UsageInstruction = "Kích rễ rau màu phát triển mạnh."
                        },
                        new
                        {
                            ProductId = 24,
                            CropId = 4,
                            UsageInstruction = "Phân bón đa năng giúp phục hồi cây cà phê sau thu hoạch."
                        },
                        new
                        {
                            ProductId = 81,
                            CropId = 4,
                            UsageInstruction = "Trừ cỏ dại trong vườn hồ tiêu, cà phê."
                        },
                        new
                        {
                            ProductId = 41,
                            CropId = 5,
                            UsageInstruction = "Trừ nấm bệnh thối củ khoai."
                        },
                        new
                        {
                            ProductId = 17,
                            CropId = 6,
                            UsageInstruction = "Tăng khả năng bám dính thuốc trên lá hoa hồng."
                        });
                });

            modelBuilder.Entity("catalog_service.Models.Product", b =>
                {
                    b.HasOne("catalog_service.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("catalog_service.Models.ProductCrop", b =>
                {
                    b.HasOne("catalog_service.Models.Crop", "Crop")
                        .WithMany("ProductCrops")
                        .HasForeignKey("CropId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("catalog_service.Models.Product", "Product")
                        .WithMany("ProductCrops")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Crop");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("catalog_service.Models.Crop", b =>
                {
                    b.Navigation("ProductCrops");
                });

            modelBuilder.Entity("catalog_service.Models.Product", b =>
                {
                    b.Navigation("ProductCrops");
                });
#pragma warning restore 612, 618
        }
    }
}
