// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using catalog_service.Data;

#nullable disable

namespace catalog_service.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    partial class CatalogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("catalog_service.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedByAdminId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("ManagedByStaffId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Phân bón và hóa chất"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Thuốc trừ bệnh"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Thuốc trừ cỏ"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Thuốc trừ sâu"
                        });
                });

            modelBuilder.Entity("catalog_service.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int?>("ChemicalProfileId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedByAdminId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("ManagedByStaffId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SKU")
                        .IsUnique();

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            ChemicalProfileId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Bo và Kẽm là các yếu tố vi lượng thiết yếu cho cây trồng...",
                            IsActive = false,
                            Name = "Vi lượng-BOROZINC",
                            SKU = "sp0001",
                            ImageUrl = "https://res.cloudinary.com/biopestcontrol/image/upload/products/sp0001.jpg",
                            UnitPrice = 180000m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            ChemicalProfileId = 26,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Thuốc trừ sâu sinh học, 100% nguồn gốc từ thực vật...",
                            IsActive = false,
                            Name = "TT-ANONIN 1EC",
                            SKU = "sp0002",
                            ImageUrl = "https://res.cloudinary.com/biopestcontrol/image/upload/products/sp0002.jpg",
                            UnitPrice = 220000m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            ChemicalProfileId = 23,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Công thức mới với khả năng tác động mạnh...",
                            IsActive = false,
                            Name = "TT SNAILTA GOLD 750WP",
                            SKU = "sp0003",
                            ImageUrl = "https://res.cloudinary.com/biopestcontrol/image/upload/products/sp0003.jpg",
                            UnitPrice = 220000m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            ChemicalProfileId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Giúp ra hoa sớm, đồng loạt...",
                            IsActive = true,
                            Name = "TANO_606",
                            SKU = "sp0004",
                            ImageUrl = "https://res.cloudinary.com/biopestcontrol/image/upload/products/sp0004.jpg",
                            UnitPrice = 130000m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Giúp cây trồng phát triển nhanh, khỏe...",
                            IsActive = false,
                            Name = "TANO_601",
                            SKU = "sp0005",
                            ImageUrl = "https://res.cloudinary.com/biopestcontrol/image/upload/products/sp0005.jpg",
                            UnitPrice = 120000m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            ChemicalProfileId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Sunphat Kẽm là muối Kẽm vô cơ...",
                            IsActive = true,
                            Name = "SUNPHAT_KẼM",
                            SKU = "sp0006",
                            ImageUrl = "https://res.cloudinary.com/biopestcontrol/image/upload/products/sp0006.jpg",
                            UnitPrice = 220000m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Tăng độ cứng cây, chống chịu sâu bệnh...",
                            IsActive = true,
                            Name = "SPC - NPK",
                            SKU = "sp0007",
                            ImageUrl = "https://res.cloudinary.com/biopestcontrol/image/upload/products/sp0007.jpg",
                            UnitPrice = 200000m
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "TT BIOBECA 0.1SP giúp giữ xanh lá đòng...",
                            IsActive = true,
                            Name = "TT BIOBECA 0.1SP",
                            SKU = "sp0008",
                            ImageUrl = "https://res.cloudinary.com/biopestcontrol/image/upload/products/sp0008.jpg",
                            UnitPrice = 190000m
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Kích thích phát triển bộ rễ...",
                            IsActive = true,
                            Name = "SPC_MKP",
                            SKU = "sp0009",
                            ImageUrl = "https://res.cloudinary.com/biopestcontrol/image/upload/products/sp0009.jpg",
                            UnitPrice = 230000m
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Hạn chế chiều cao cây...",
                            IsActive = true,
                            Name = "SPC_KALI_SILIC",
                            SKU = "sp0010",
                            ImageUrl = "https://res.cloudinary.com/biopestcontrol/image/upload/products/sp0010.jpg",
                            UnitPrice = 250000m
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "SAMINO 5.1 SL là chất kích thích sinh học...",
                            IsActive = true,
                            Name = "SAMINO_51SL",
                            SKU = "sp0011",
                            ImageUrl = "https://res.cloudinary.com/biopestcontrol/image/upload/products/sp0011.jpg",
                            UnitPrice = 210000m
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 1,
                            ChemicalProfileId = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "SAIGON - P1 giúp tăng cường đẻ nhánh...",
                            IsActive = true,
                            Name = "SAIGON_P115WP",
                            SKU = "sp0012",
                            ImageUrl = "https://res.cloudinary.com/biopestcontrol/image/upload/products/sp0012.jpg",
                            UnitPrice = 260000m
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 1,
                            ChemicalProfileId = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "SAGOLATEX 2.5 PA là thuốc kích thích...",
                            IsActive = true,
                            Name = "SAGOLATEX",
                            SKU = "sp0013",
                            ImageUrl = "https://res.cloudinary.com/biopestcontrol/image/upload/products/sp0013.jpg",
                            UnitPrice = 190000m
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Giúp thuốc BVTV loang trải đều...",
                            IsActive = true,
                            Name = "SAGO SÓNG THẦN",
                            SKU = "sp0014",
                            ImageUrl = "https://res.cloudinary.com/biopestcontrol/image/upload/products/sp0014.jpg",
                            UnitPrice = 195000m
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 1,
                            ChemicalProfileId = 17,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "SAGO ĐỒNG được sử dụng để pha chế...",
                            IsActive = false,
                            Name = "SAGO ĐỒNG",
                            SKU = "sp0015",
                            ImageUrl = "https://res.cloudinary.com/biopestcontrol/image/upload/products/sp0015.jpg",
                            UnitPrice = 250000m
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Đang cập nhật",
                            IsActive = true,
                            Name = "SAGO SIÊU HẤP",
                            SKU = "sp0016",
                            ImageUrl = "https://res.cloudinary.com/biopestcontrol/image/upload/products/sp0016.jpg",
                            UnitPrice = 220000m
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Tăng khả năng bám dính...",
                            IsActive = true,
                            Name = "SAGO BÁM DÍNH",
                            SKU = "sp0017",
                            ImageUrl = "https://res.cloudinary.com/biopestcontrol/image/upload/products/sp0017.jpg",
                            UnitPrice = 300000m
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Giúp phát triển bộ rễ khỏe...",
                            IsActive = true,
                            Name = "PLASTIMULA 1SL",
                            SKU = "sp0018",
                            ImageUrl = "https://res.cloudinary.com/biopestcontrol/image/upload/products/sp0018.jpg",
                            UnitPrice = 230000m
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Giúp phá vỡ trạng thái ngủ...",
                            IsActive = true,
                            Name = "SAGO AXIT",
                            SKU = "sp0019",
                            ImageUrl = "https://res.cloudinary.com/biopestcontrol/image/upload/products/sp0019.jpg",
                            UnitPrice = 180000m
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Giúp đất tơi xốp, giàu mùn...",
                            IsActive = true,
                            Name = "ORGANIC NOKAYO",
                            SKU = "sp0020",
                            ImageUrl = "https://res.cloudinary.com/biopestcontrol/image/upload/products/sp0020.jpg",
                            UnitPrice = 170000m
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Bổ sung hữu cơ cho đất bạc màu...",
                            IsActive = true,
                            Name = "ORGANIC YUKIMOTO",
                            SKU = "sp0021",
                            ImageUrl = "https://res.cloudinary.com/biopestcontrol/image/upload/products/sp0021.jpg",
                            UnitPrice = 180000m
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cung cấp dinh dưỡng cân đối...",
                            IsActive = true,
                            Name = "NPK HÀN VIỆT 20 20 15 TE",
                            SKU = "sp0022",
                            ImageUrl = "https://res.cloudinary.com/biopestcontrol/image/upload/products/sp0022.jpg",
                            UnitPrice = 210000m
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Thúc đẩy cây trồng phát triển đồng đều...",
                            IsActive = true,
                            Name = "NPK HÀN VIỆT 15-15-15",
                            SKU = "sp0023",
                            ImageUrl = "https://res.cloudinary.com/biopestcontrol/image/upload/products/sp0023.jpg",
                            UnitPrice = 210000m
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "FERTIGONIA là phân bón đa năng...",
                            IsActive = true,
                            Name = "NPK FERTIGONIA",
                            SKU = "sp0024",
                            ImageUrl = "https://res.cloudinary.com/biopestcontrol/image/upload/products/sp0024.jpg",
                            UnitPrice = 310000m
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Natrazyme bổ sung đầy đủ và cân đối...",
                            IsActive = true,
                            Name = "NATRAZYME",
                            SKU = "sp0025",
                            ImageUrl = "https://res.cloudinary.com/biopestcontrol/image/upload/products/sp0025.jpg",
                            UnitPrice = 230000m
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cung cấp dinh dưỡng cân đối...",
                            IsActive = true,
                            Name = "NPK 16-16-8-13S",
                            SKU = "sp0026",
                            ImageUrl = "https://res.cloudinary.com/biopestcontrol/image/upload/products/sp0026.jpg",
                            UnitPrice = 210000m
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Tăng sức chống chịu cho cây trồng...",
                            IsActive = true,
                            Name = "SOP",
                            SKU = "sp0027",
                            ImageUrl = "https://res.cloudinary.com/biopestcontrol/image/upload/products/sp0027.jpg",
                            UnitPrice = 240000m
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Phân bón hỗn hợp NPK...",
                            IsActive = true,
                            Name = "NPK 17-7-17 + TE",
                            SKU = "sp0028",
                            ImageUrl = "https://res.cloudinary.com/biopestcontrol/image/upload/products/sp0028.jpg",
                            UnitPrice = 200000m
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Phân NPK sản xuất bằng công nghệ...",
                            IsActive = true,
                            Name = "NPK 16-16-8 + TE",
                            SKU = "sp0029",
                            ImageUrl = "https://res.cloudinary.com/biopestcontrol/image/upload/products/sp0029.jpg",
                            UnitPrice = 190000m
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cung cấp đồng thời Đạm – Lân – Kali...",
                            IsActive = true,
                            Name = "NPK TÂN THÀNH 25-25-5",
                            SKU = "sp0030",
                            ImageUrl = "https://res.cloudinary.com/biopestcontrol/image/upload/products/sp0030.jpg",
                            UnitPrice = 310000m
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Phân đa dinh dưỡng tổng hợp...",
                            IsActive = true,
                            Name = "NPK TÂN THÀNH 20-20-15 TE",
                            SKU = "sp0031",
                            ImageUrl = "https://res.cloudinary.com/biopestcontrol/image/upload/products/sp0031.jpg",
                            UnitPrice = 220000m
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Thuốc sinh học giúp tăng năng suất lúa...",
                            IsActive = true,
                            Name = "LACASOTO 4SP",
                            SKU = "sp0032",
                            ImageUrl = "https://res.cloudinary.com/biopestcontrol/image/upload/products/sp0032.jpg",
                            UnitPrice = 210000m
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Polyphenol giúp cây trồng...",
                            IsActive = true,
                            Name = "CHUBECA",
                            SKU = "sp0033",
                            ImageUrl = "https://res.cloudinary.com/biopestcontrol/image/upload/products/sp0033.jpg",
                            UnitPrice = 170000m
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cung cấp dinh dưỡng thiết yếu...",
                            IsActive = true,
                            Name = "DAP TÂN THÀNH",
                            SKU = "sp0034",
                            ImageUrl = "https://res.cloudinary.com/biopestcontrol/image/upload/products/sp0034.jpg",
                            UnitPrice = 160000m
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cải tạo đất, tăng độ tơi xốp...",
                            IsActive = true,
                            Name = "ATRAZIN",
                            SKU = "sp0035",
                            ImageUrl = "https://res.cloudinary.com/biopestcontrol/image/upload/products/sp0035.jpg",
                            UnitPrice = 230000m
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 1,
                            ChemicalProfileId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Kẽm và Boron có vai trò thiết yếu...",
                            IsActive = true,
                            Name = "KẼM BORON",
                            SKU = "sp0036",
                            ImageUrl = "https://res.cloudinary.com/biopestcontrol/image/upload/products/sp0036.jpg",
                            UnitPrice = 200000m
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 1,
                            ChemicalProfileId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Bo và Kẽm có vai trò thiết yếu...",
                            IsActive = true,
                            Name = "ANIMAT",
                            SKU = "sp0037",
                            ImageUrl = "https://res.cloudinary.com/biopestcontrol/image/upload/products/sp0037.jpg",
                            UnitPrice = 230000m
                        },
                        new
                        {
                            Id = 38,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Giúp kích thích phát triển bộ rễ...",
                            IsActive = true,
                            Name = "SPC - MKP",
                            SKU = "sp0038",
                            ImageUrl = "https://res.cloudinary.com/biopestcontrol/image/upload/products/sp0038.jpg",
                            UnitPrice = 210000m
                        },
                        new
                        {
                            Id = 39,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Chocaso là thuốc tăng trưởng sinh học...",
                            IsActive = true,
                            Name = "CHOCASO",
                            SKU = "sp0039",
                            ImageUrl = "https://res.cloudinary.com/biopestcontrol/image/upload/products/sp0039.jpg",
                            UnitPrice = 300000m
                        },
                        new
                        {
                            Id = 40,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Phân NPK sản xuất theo công nghệ...",
                            IsActive = true,
                            Name = "NKP TE",
                            SKU = "sp0040",
                            ImageUrl = "https://res.cloudinary.com/biopestcontrol/image/upload/products/sp0040.jpg",
                            UnitPrice = 230000m
                        },
                        new
                        {
                            Id = 41,
                            CategoryId = 2,
                            ChemicalProfileId = 12,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Thuốc trừ nấm tiếp xúc...",
                            IsActive = true,
                            Name = "ZINEB BUL 80WP",
                            SKU = "sp0041",
                            ImageUrl = "https://res.cloudinary.com/biopestcontrol/image/upload/products/sp0041.jpg",
                            UnitPrice = 170000m
                        },
                        new
                        {
                            Id = 42,
                            CategoryId = 2,
                            ChemicalProfileId = 12,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Thuốc trừ nấm tác dụng tiếp xúc...",
                            IsActive = true,
                            Name = "ZIN 80 WP",
                            SKU = "sp0042",
                            ImageUrl = "https://res.cloudinary.com/biopestcontrol/image/upload/products/sp0042.jpg",
                            UnitPrice = 210000m
                        },
                        new
                        {
                            Id = 43,
                            CategoryId = 2,
                            ChemicalProfileId = 15,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "XINAZO 250 SC là thuốc trừ nấm...",
                            IsActive = true,
                            Name = "XINAZO",
                            SKU = "sp0043",
                            ImageUrl = "https://res.cloudinary.com/biopestcontrol/image/upload/products/sp0043.jpg",
                            UnitPrice = 200000m
                        },
                        new
                        {
                            Id = 44,
                            CategoryId = 2,
                            ChemicalProfileId = 14,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "VANICIDE là thuốc trừ bệnh sinh học...",
                            IsActive = true,
                            Name = "VANICIDE",
                            SKU = "sp0044",
                            ImageUrl = "https://res.cloudinary.com/biopestcontrol/image/upload/products/sp0044.jpg",
                            UnitPrice = 175000m
                        },
                        new
                        {
                            Id = 45,
                            CategoryId = 2,
                            ChemicalProfileId = 14,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Thuốc có tác dụng nội hấp mạnh...",
                            IsActive = true,
                            Name = "UNITIL",
                            SKU = "sp0045",
                            ImageUrl = "https://res.cloudinary.com/biopestcontrol/image/upload/products/sp0045.jpg",
                            UnitPrice = 260000m
                        },
                        new
                        {
                            Id = 46,
                            CategoryId = 2,
                            ChemicalProfileId = 16,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Thuốc đặc trị vi khuẩn...",
                            IsActive = true,
                            Name = "BASU 250WP",
                            SKU = "sp0046",
                            ImageUrl = "https://res.cloudinary.com/biopestcontrol/image/upload/products/sp0046.jpg",
                            UnitPrice = 150000m
                        },
                        new
                        {
                            Id = 47,
                            CategoryId = 1,
                            ChemicalProfileId = 15,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Công thức mới đặc trị bệnh đạo ôn...",
                            IsActive = true,
                            Name = "KEEP 300SC",
                            SKU = "sp0047",
                            ImageUrl = "https://res.cloudinary.com/biopestcontrol/image/upload/products/sp0047.jpg",
                            UnitPrice = 175000m
                        },
                        new
                        {
                            Id = 48,
                            CategoryId = 2,
                            ChemicalProfileId = 16,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Thuốc đặc trị bệnh cháy bìa lá...",
                            IsActive = false,
                            Name = "ATANIL",
                            SKU = "sp0048",
                            ImageUrl = "https://res.cloudinary.com/biopestcontrol/image/upload/products/sp0048.jpg",
                            UnitPrice = 230000m
                        },
                        new
                        {
                            Id = 49,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Thuốc có tác dụng tiếp xúc và nội hấp...",
                            IsActive = true,
                            Name = "BIOMYCIN",
                            SKU = "sp0049",
                            ImageUrl = "https://res.cloudinary.com/biopestcontrol/image/upload/products/sp0049.jpg",
                            UnitPrice = 185000m
                        },
                        new
                        {
                            Id = 50,
                            CategoryId = 4,
                            ChemicalProfileId = 5,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Thuốc trừ sâu Regent là sản phẩm đặc trị...",
                            IsActive = true,
                            Name = "Regent",
                            SKU = "sp0050",
                            ImageUrl = "https://res.cloudinary.com/biopestcontrol/image/upload/products/sp0050.jpg",
                            UnitPrice = 199000m
                        },
                        new
                        {
                            Id = 51,
                            CategoryId = 2,
                            ChemicalProfileId = 11,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Trizole 400 SC là thuốc trừ nấm...",
                            IsActive = true,
                            Name = "TRIZOLE 400SC",
                            SKU = "sp0051",
                            ImageUrl = "https://res.cloudinary.com/biopestcontrol/image/upload/products/sp0051.jpg",
                            UnitPrice = 210000m
                        },
                        new
                        {
                            Id = 52,
                            CategoryId = 2,
                            ChemicalProfileId = 11,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Trizole 75WP là thuốc trừ nấm...",
                            IsActive = true,
                            Name = "TRIZOLE 75WP",
                            SKU = "sp0052",
                            ImageUrl = "https://res.cloudinary.com/biopestcontrol/image/upload/products/sp0052.jpg",
                            UnitPrice = 260000m
                        },
                        new
                        {
                            Id = 53,
                            CategoryId = 2,
                            ChemicalProfileId = 11,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Trizole 75 DO là thuốc trừ nấm...",
                            IsActive = true,
                            Name = "TRIZOLE 75 DO",
                            SKU = "sp0053",
                            ImageUrl = "https://res.cloudinary.com/biopestcontrol/image/upload/products/sp0053.jpg",
                            UnitPrice = 240000m
                        },
                        new
                        {
                            Id = 54,
                            CategoryId = 2,
                            ChemicalProfileId = 11,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "TRI 75WG là thuốc trừ bệnh lưu dẫn...",
                            IsActive = true,
                            Name = "TRI 75WG",
                            SKU = "sp0054",
                            ImageUrl = "https://res.cloudinary.com/biopestcontrol/image/upload/products/sp0054.jpg",
                            UnitPrice = 240000m
                        },
                        new
                        {
                            Id = 55,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "TREPPACH BUL là thuốc trừ nấm...",
                            IsActive = true,
                            Name = "TREPPACH BUL",
                            SKU = "sp0055",
                            ImageUrl = "https://res.cloudinary.com/biopestcontrol/image/upload/products/sp0055.jpg",
                            UnitPrice = 220000m
                        },
                        new
                        {
                            Id = 56,
                            CategoryId = 2,
                            ChemicalProfileId = 15,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "SAIPORA là thuốc trừ nấm...",
                            IsActive = true,
                            Name = "SAIPORA",
                            SKU = "sp0056",
                            ImageUrl = "https://res.cloudinary.com/biopestcontrol/image/upload/products/sp0056.jpg",
                            UnitPrice = 210000m
                        },
                        new
                        {
                            Id = 57,
                            CategoryId = 2,
                            ChemicalProfileId = 15,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "SAGOPERFECT 320 là thuốc trừ nấm...",
                            IsActive = true,
                            Name = "SAGOPERFECT 320",
                            SKU = "sp0057",
                            ImageUrl = "https://res.cloudinary.com/biopestcontrol/image/upload/products/sp0057.jpg",
                            UnitPrice = 270000m
                        },
                        new
                        {
                            Id = 58,
                            CategoryId = 2,
                            ChemicalProfileId = 15,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Diệt mầm bệnh nhanh chóng...",
                            IsActive = true,
                            Name = "SAGOGRAIN 300EC",
                            SKU = "sp0058",
                            ImageUrl = "https://res.cloudinary.com/biopestcontrol/image/upload/products/sp0058.jpg",
                            UnitPrice = 310000m
                        },
                        new
                        {
                            Id = 59,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "ROTEVA 30SC giúp trị bệnh...",
                            IsActive = true,
                            Name = "ROTEVA 30SC",
                            SKU = "sp0059",
                            ImageUrl = "https://res.cloudinary.com/biopestcontrol/image/upload/products/sp0059.jpg",
                            UnitPrice = 150000m
                        },
                        new
                        {
                            Id = 60,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Thuốc có tác dụng phòng và trị bệnh...",
                            IsActive = true,
                            Name = "PYROLAX 250EC",
                            SKU = "sp0060",
                            ImageUrl = "https://res.cloudinary.com/biopestcontrol/image/upload/products/sp0060.jpg",
                            UnitPrice = 210000m
                        },
                        new
                        {
                            Id = 61,
                            CategoryId = 2,
                            ChemicalProfileId = 17,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Thuốc phòng trị hiệu quả...",
                            IsActive = true,
                            Name = "OTICIN 47.5WP",
                            SKU = "sp0061",
                            ImageUrl = "https://res.cloudinary.com/biopestcontrol/image/upload/products/sp0061.jpg",
                            UnitPrice = 240000m
                        },
                        new
                        {
                            Id = 62,
                            CategoryId = 2,
                            ChemicalProfileId = 12,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Thuốc phòng trị hiệu quả...",
                            IsActive = true,
                            Name = "MEXYL MZ",
                            SKU = "sp0062",
                            ImageUrl = "https://res.cloudinary.com/biopestcontrol/image/upload/products/sp0062.jpg",
                            UnitPrice = 140000m
                        },
                        new
                        {
                            Id = 63,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Thuốc có tác dụng phòng trị...",
                            IsActive = true,
                            Name = "LUSTER 250SC",
                            SKU = "sp0063",
                            ImageUrl = "https://res.cloudinary.com/biopestcontrol/image/upload/products/sp0063.jpg",
                            UnitPrice = 250000m
                        },
                        new
                        {
                            Id = 64,
                            CategoryId = 2,
                            ChemicalProfileId = 15,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Giúp diệt nấm bệnh nhanh chóng...",
                            IsActive = true,
                            Name = "LUNASA 80",
                            SKU = "sp0064",
                            ImageUrl = "https://res.cloudinary.com/biopestcontrol/image/upload/products/sp0064.jpg",
                            UnitPrice = 220000m
                        },
                        new
                        {
                            Id = 65,
                            CategoryId = 2,
                            ChemicalProfileId = 11,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Thuốc có hiệu quả cao...",
                            IsActive = true,
                            Name = "LÚA VÀNG",
                            SKU = "sp0065",
                            ImageUrl = "https://res.cloudinary.com/biopestcontrol/image/upload/products/sp0065.jpg",
                            UnitPrice = 260000m
                        },
                        new
                        {
                            Id = 66,
                            CategoryId = 2,
                            ChemicalProfileId = 18,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Thuốc trừ nấm nội hấp...",
                            IsActive = true,
                            Name = "KAISAIGON",
                            SKU = "sp0066",
                            ImageUrl = "https://res.cloudinary.com/biopestcontrol/image/upload/products/sp0066.jpg",
                            UnitPrice = 230000m
                        },
                        new
                        {
                            Id = 67,
                            CategoryId = 2,
                            ChemicalProfileId = 18,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Thuốc đặc trị các bệnh nấm...",
                            IsActive = true,
                            Name = "KAISAIGON 10",
                            SKU = "sp0067",
                            ImageUrl = "https://res.cloudinary.com/biopestcontrol/image/upload/products/sp0067.jpg",
                            UnitPrice = 150000m
                        },
                        new
                        {
                            Id = 68,
                            CategoryId = 2,
                            ChemicalProfileId = 17,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Thuốc phòng trị hiệu quả...",
                            IsActive = true,
                            Name = "CỐP XANH",
                            SKU = "sp0068",
                            ImageUrl = "https://res.cloudinary.com/biopestcontrol/image/upload/products/sp0068.jpg",
                            UnitPrice = 250000m
                        },
                        new
                        {
                            Id = 69,
                            CategoryId = 2,
                            ChemicalProfileId = 16,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "HỎA TIỄN 50 SP là thuốc trừ bệnh...",
                            IsActive = true,
                            Name = "HỎA TIỄN",
                            SKU = "sp0069",
                            ImageUrl = "https://res.cloudinary.com/biopestcontrol/image/upload/products/sp0069.jpg",
                            UnitPrice = 250000m
                        },
                        new
                        {
                            Id = 70,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "HẠT VÀNG có khả năng phòng và trị...",
                            IsActive = true,
                            Name = "HẠT VÀNG",
                            SKU = "sp0070",
                            ImageUrl = "https://res.cloudinary.com/biopestcontrol/image/upload/products/sp0070.jpg",
                            UnitPrice = 215000m
                        },
                        new
                        {
                            Id = 71,
                            CategoryId = 2,
                            ChemicalProfileId = 11,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Edivil 80WP là sự kết hợp...",
                            IsActive = true,
                            Name = "EDIVIL 80WP",
                            SKU = "sp0071",
                            ImageUrl = "https://res.cloudinary.com/biopestcontrol/image/upload/products/sp0071.jpg",
                            UnitPrice = 210000m
                        },
                        new
                        {
                            Id = 72,
                            CategoryId = 2,
                            ChemicalProfileId = 12,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "DIPOMATE 430 SC là thuốc trừ nấm...",
                            IsActive = true,
                            Name = "DIPOMATE",
                            SKU = "sp0072",
                            ImageUrl = "https://res.cloudinary.com/biopestcontrol/image/upload/products/sp0072.jpg",
                            UnitPrice = 220000m
                        },
                        new
                        {
                            Id = 73,
                            CategoryId = 2,
                            ChemicalProfileId = 12,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Phòng trị hiệu quả nhiều bệnh...",
                            IsActive = true,
                            Name = "DIPOMATE 80",
                            SKU = "sp0073",
                            ImageUrl = "https://res.cloudinary.com/biopestcontrol/image/upload/products/sp0073.jpg",
                            UnitPrice = 130000m
                        },
                        new
                        {
                            Id = 74,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "CLEARNER 75 WP là thuốc trừ nấm...",
                            IsActive = true,
                            Name = "CLEARNER 75 WP",
                            SKU = "sp0074",
                            ImageUrl = "https://res.cloudinary.com/biopestcontrol/image/upload/products/sp0074.jpg",
                            UnitPrice = 210000m
                        },
                        new
                        {
                            Id = 75,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Đặc trị lem lép hạt trên lúa...",
                            IsActive = true,
                            Name = "CHUBECA 1.8SL",
                            SKU = "sp0075",
                            ImageUrl = "https://res.cloudinary.com/biopestcontrol/image/upload/products/sp0075.jpg",
                            UnitPrice = 130000m
                        },
                        new
                        {
                            Id = 76,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "ALPINE có tác dụng lưu dẫn...",
                            IsActive = true,
                            Name = "ALPINE 80WP",
                            SKU = "sp0076",
                            ImageUrl = "https://res.cloudinary.com/biopestcontrol/image/upload/products/sp0076.jpg",
                            UnitPrice = 220000m
                        },
                        new
                        {
                            Id = 77,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "ALPINE 80 WG là thuốc trừ nấm...",
                            IsActive = true,
                            Name = "ALPINE XANH",
                            SKU = "sp0077",
                            ImageUrl = "https://res.cloudinary.com/biopestcontrol/image/upload/products/sp0077.jpg",
                            UnitPrice = 220000m
                        },
                        new
                        {
                            Id = 78,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Đặc trị bệnh phấn trắng...",
                            IsActive = true,
                            Name = "SULOX 80WP",
                            SKU = "sp0078",
                            ImageUrl = "https://res.cloudinary.com/biopestcontrol/image/upload/products/sp0078.jpg",
                            UnitPrice = 210000m
                        },
                        new
                        {
                            Id = 79,
                            CategoryId = 2,
                            ChemicalProfileId = 13,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Thuốc trừ nấm có khả năng nội hấp...",
                            IsActive = true,
                            Name = "SAIZOLE 5SC",
                            SKU = "sp0079",
                            ImageUrl = "https://res.cloudinary.com/biopestcontrol/image/upload/products/sp0079.jpg",
                            UnitPrice = 310000m
                        },
                        new
                        {
                            Id = 80,
                            CategoryId = 2,
                            ChemicalProfileId = 14,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Thuốc trừ nấm và vi khuẩn...",
                            IsActive = true,
                            Name = "SAIPAN 2SL",
                            SKU = "sp0080",
                            ImageUrl = "https://res.cloudinary.com/biopestcontrol/image/upload/products/sp0080.jpg",
                            UnitPrice = 220000m
                        },
                        new
                        {
                            Id = 81,
                            CategoryId = 3,
                            ChemicalProfileId = 19,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Thuốc trừ cỏ không chọn lọc...",
                            IsActive = true,
                            Name = "YOSKY",
                            SKU = "sp0081",
                            ImageUrl = "https://res.cloudinary.com/biopestcontrol/image/upload/products/sp0081.jpg",
                            UnitPrice = 310000m
                        },
                        new
                        {
                            Id = 82,
                            CategoryId = 3,
                            ChemicalProfileId = 22,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Thuốc được dùng để diệt cỏ...",
                            IsActive = true,
                            Name = "XINRON",
                            SKU = "sp0082",
                            ImageUrl = "https://res.cloudinary.com/biopestcontrol/image/upload/products/sp0082.jpg",
                            UnitPrice = 250000m
                        },
                        new
                        {
                            Id = 83,
                            CategoryId = 3,
                            ChemicalProfileId = 21,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Diệt hầu hết các loại cỏ dại...",
                            IsActive = true,
                            Name = "VITOP",
                            SKU = "sp0083",
                            ImageUrl = "https://res.cloudinary.com/biopestcontrol/image/upload/products/sp0083.jpg",
                            UnitPrice = 310000m
                        });
                });

            modelBuilder.Entity("catalog_service.Models.Product", b =>
                {
                    b.HasOne("catalog_service.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}

