// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using identity_service.Data;

#nullable disable

namespace identity_service.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260507033418_SimplifyStaffEntity")]
    partial class SimplifyStaffEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("identity_service.Models.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("GroupCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "customers.view_list",
                            DisplayName = "Xem danh sách khách hàng",
                            DisplayOrder = 1,
                            GroupCode = "UC14",
                            GroupName = "UC14 - Quản lý khách hàng",
                            IsActive = true
                        },
                        new
                        {
                            Id = 2,
                            Code = "customers.view_detail",
                            DisplayName = "Xem chi tiết khách hàng",
                            DisplayOrder = 2,
                            GroupCode = "UC14",
                            GroupName = "UC14 - Quản lý khách hàng",
                            IsActive = true
                        },
                        new
                        {
                            Id = 3,
                            Code = "customers.search",
                            DisplayName = "Tìm kiếm khách hàng",
                            DisplayOrder = 3,
                            GroupCode = "UC14",
                            GroupName = "UC14 - Quản lý khách hàng",
                            IsActive = true
                        },
                        new
                        {
                            Id = 4,
                            Code = "customers.edit",
                            DisplayName = "Chỉnh sửa khách hàng",
                            DisplayOrder = 4,
                            GroupCode = "UC14",
                            GroupName = "UC14 - Quản lý khách hàng",
                            IsActive = true
                        },
                        new
                        {
                            Id = 5,
                            Code = "customers.lock",
                            DisplayName = "Khóa tài khoản khách hàng",
                            DisplayOrder = 5,
                            GroupCode = "UC14",
                            GroupName = "UC14 - Quản lý khách hàng",
                            IsActive = true
                        },
                        new
                        {
                            Id = 6,
                            Code = "orders.view_list",
                            DisplayName = "Xem danh sách đơn hàng",
                            DisplayOrder = 1,
                            GroupCode = "UC15",
                            GroupName = "UC15 - Quản lý đơn hàng",
                            IsActive = true
                        },
                        new
                        {
                            Id = 7,
                            Code = "orders.view_detail",
                            DisplayName = "Xem chi tiết đơn hàng",
                            DisplayOrder = 2,
                            GroupCode = "UC15",
                            GroupName = "UC15 - Quản lý đơn hàng",
                            IsActive = true
                        },
                        new
                        {
                            Id = 8,
                            Code = "orders.search",
                            DisplayName = "Tìm kiếm đơn hàng",
                            DisplayOrder = 3,
                            GroupCode = "UC15",
                            GroupName = "UC15 - Quản lý đơn hàng",
                            IsActive = true
                        },
                        new
                        {
                            Id = 9,
                            Code = "orders.update_delivery",
                            DisplayName = "Cập nhật giao hàng",
                            DisplayOrder = 4,
                            GroupCode = "UC15",
                            GroupName = "UC15 - Quản lý đơn hàng",
                            IsActive = true
                        },
                        new
                        {
                            Id = 10,
                            Code = "articles.filter",
                            DisplayName = "Lọc bài viết / tin tức",
                            DisplayOrder = 1,
                            GroupCode = "UC16",
                            GroupName = "UC16 - Quản lý bài viết",
                            IsActive = true
                        },
                        new
                        {
                            Id = 11,
                            Code = "articles.view",
                            DisplayName = "Xem bài viết / tin tức",
                            DisplayOrder = 2,
                            GroupCode = "UC16",
                            GroupName = "UC16 - Quản lý bài viết",
                            IsActive = true
                        },
                        new
                        {
                            Id = 12,
                            Code = "articles.create",
                            DisplayName = "Tạo bài viết / tin tức",
                            DisplayOrder = 3,
                            GroupCode = "UC16",
                            GroupName = "UC16 - Quản lý bài viết",
                            IsActive = true
                        },
                        new
                        {
                            Id = 13,
                            Code = "articles.edit",
                            DisplayName = "Chỉnh sửa bài viết",
                            DisplayOrder = 4,
                            GroupCode = "UC16",
                            GroupName = "UC16 - Quản lý bài viết",
                            IsActive = true
                        },
                        new
                        {
                            Id = 14,
                            Code = "articles.delete",
                            DisplayName = "Xóa bài viết / tin tức",
                            DisplayOrder = 5,
                            GroupCode = "UC16",
                            GroupName = "UC16 - Quản lý bài viết",
                            IsActive = true
                        },
                        new
                        {
                            Id = 15,
                            Code = "products.filter",
                            DisplayName = "Lọc sản phẩm",
                            DisplayOrder = 1,
                            GroupCode = "UC17",
                            GroupName = "UC17 - Quản lý sản phẩm",
                            IsActive = true
                        },
                        new
                        {
                            Id = 16,
                            Code = "products.search",
                            DisplayName = "Tìm kiếm sản phẩm",
                            DisplayOrder = 2,
                            GroupCode = "UC17",
                            GroupName = "UC17 - Quản lý sản phẩm",
                            IsActive = true
                        },
                        new
                        {
                            Id = 17,
                            Code = "products.view_detail",
                            DisplayName = "Xem chi tiết sản phẩm",
                            DisplayOrder = 3,
                            GroupCode = "UC17",
                            GroupName = "UC17 - Quản lý sản phẩm",
                            IsActive = true
                        },
                        new
                        {
                            Id = 18,
                            Code = "products.view_list",
                            DisplayName = "Xem danh sách sản phẩm",
                            DisplayOrder = 4,
                            GroupCode = "UC17",
                            GroupName = "UC17 - Quản lý sản phẩm",
                            IsActive = true
                        },
                        new
                        {
                            Id = 19,
                            Code = "products.view_feedback",
                            DisplayName = "Xem phản hồi sản phẩm",
                            DisplayOrder = 5,
                            GroupCode = "UC17",
                            GroupName = "UC17 - Quản lý sản phẩm",
                            IsActive = true
                        },
                        new
                        {
                            Id = 20,
                            Code = "products.reply_feedback",
                            DisplayName = "Trả lời phản hồi sản phẩm",
                            DisplayOrder = 6,
                            GroupCode = "UC17",
                            GroupName = "UC17 - Quản lý sản phẩm",
                            IsActive = true
                        },
                        new
                        {
                            Id = 21,
                            Code = "categories.view",
                            DisplayName = "Xem danh mục sản phẩm",
                            DisplayOrder = 1,
                            GroupCode = "UC18",
                            GroupName = "UC18 - Quản lý danh mục",
                            IsActive = true
                        },
                        new
                        {
                            Id = 22,
                            Code = "categories.search",
                            DisplayName = "Tìm kiếm danh mục",
                            DisplayOrder = 2,
                            GroupCode = "UC18",
                            GroupName = "UC18 - Quản lý danh mục",
                            IsActive = true
                        },
                        new
                        {
                            Id = 23,
                            Code = "warehouse.view",
                            DisplayName = "Xem kho hàng",
                            DisplayOrder = 1,
                            GroupCode = "UC19",
                            GroupName = "UC19 - Quản lý kho",
                            IsActive = true
                        },
                        new
                        {
                            Id = 24,
                            Code = "warehouse.filter",
                            DisplayName = "Lọc kho hàng",
                            DisplayOrder = 2,
                            GroupCode = "UC19",
                            GroupName = "UC19 - Quản lý kho",
                            IsActive = true
                        },
                        new
                        {
                            Id = 25,
                            Code = "chemical_safety.view",
                            DisplayName = "Xem an toàn hóa chất",
                            DisplayOrder = 1,
                            GroupCode = "UC20",
                            GroupName = "UC20 - An toàn hóa chất",
                            IsActive = true
                        },
                        new
                        {
                            Id = 26,
                            Code = "chemical_safety.search",
                            DisplayName = "Tìm kiếm an toàn hóa chất",
                            DisplayOrder = 2,
                            GroupCode = "UC20",
                            GroupName = "UC20 - An toàn hóa chất",
                            IsActive = true
                        },
                        new
                        {
                            Id = 27,
                            Code = "chemical_safety.filter",
                            DisplayName = "Lọc an toàn hóa chất",
                            DisplayOrder = 3,
                            GroupCode = "UC20",
                            GroupName = "UC20 - An toàn hóa chất",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("identity_service.Models.Staff", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedByAdminId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsFullAccess")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedByAdminId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Staffs");
                });

            modelBuilder.Entity("identity_service.Models.StaffPermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("GrantedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("GrantedByAdminId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.Property<Guid>("StaffId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("StaffId", "PermissionId")
                        .IsUnique();

                    b.ToTable("StaffPermissions");
                });

            modelBuilder.Entity("identity_service.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FullName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("GoogleId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("identity_service.Models.Staff", b =>
                {
                    b.HasOne("identity_service.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("identity_service.Models.StaffPermission", b =>
                {
                    b.HasOne("identity_service.Models.Permission", "Permission")
                        .WithMany("StaffPermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("identity_service.Models.Staff", "Staff")
                        .WithMany("StaffPermissions")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("identity_service.Models.Permission", b =>
                {
                    b.Navigation("StaffPermissions");
                });

            modelBuilder.Entity("identity_service.Models.Staff", b =>
                {
                    b.Navigation("StaffPermissions");
                });
#pragma warning restore 612, 618
        }
    }
}
