services:
  article-service:
    build:
      context: .
      dockerfile: Dockerfile
      # Đảm bảo KHÔNG có dòng 'target: build' ở đây
    image: article-service:latest
    container_name: article-service
    ports:
      - "8081:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development