// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using agri_expert_service.Data;

#nullable disable

namespace agri_expert_service.Migrations
{
    [DbContext(typeof(AgriDbContext))]
    partial class AgriDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("agri_expert_service.Models.ChemicalProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CasNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ChemicalFormula")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ChemicalGroup")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SafetyNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("TargetCrops")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TargetPests")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ToxicityLevel")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UsageMethod")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("VietnameseName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CasNumber")
                        .IsUnique()
                        .HasFilter("[CasNumber] IS NOT NULL");

                    b.HasIndex("Name");

                    b.ToTable("ChemicalProfiles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CasNumber = "7440-42-8",
                            ChemicalGroup = "Vi lượng / Phân bón",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Nguyên tố vi lượng cần thiết cho sự phát triển của thực vật.",
                            IsActive = true,
                            Name = "Boron",
                            ToxicityLevel = "III",
                            VietnameseName = "Bo"
                        },
                        new
                        {
                            Id = 2,
                            CasNumber = "7733-02-0",
                            ChemicalGroup = "Vi lượng / Phân bón",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cung cấp kẽm cho cây trồng, khắc phục thiếu vi lượng.",
                            IsActive = true,
                            Name = "Zinc Sulfate",
                            ToxicityLevel = "III",
                            VietnameseName = "Kẽm sunfat"
                        },
                        new
                        {
                            Id = 3,
                            CasNumber = "16672-87-0",
                            ChemicalGroup = "Điều hòa sinh trưởng",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Chất điều hòa sinh trưởng kích thích chín trái, ra hoa.",
                            IsActive = true,
                            Name = "Ethephon",
                            ToxicityLevel = "II",
                            VietnameseName = "Ethephon"
                        },
                        new
                        {
                            Id = 4,
                            CasNumber = "76738-62-0",
                            ChemicalGroup = "Điều hòa sinh trưởng",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ức chế sinh trưởng chiều cao, kích thích ra hoa.",
                            IsActive = true,
                            Name = "Paclobutrazol",
                            ToxicityLevel = "III",
                            VietnameseName = "Paclobutrazol"
                        },
                        new
                        {
                            Id = 5,
                            CasNumber = "120068-37-3",
                            ChemicalGroup = "Thuốc trừ sâu",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Thuốc trừ sâu phổ rộng, tác dụng tiếp xúc và vị độc.",
                            IsActive = true,
                            Name = "Fipronil",
                            SafetyNotes = "Rất độc với cá và động vật thủy sinh.",
                            ToxicityLevel = "II",
                            VietnameseName = "Fipronil"
                        },
                        new
                        {
                            Id = 6,
                            CasNumber = "5598-13-0",
                            ChemicalGroup = "Thuốc trừ sâu",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Nhóm organophosphate, trừ sâu tiếp xúc và vị độc.",
                            IsActive = true,
                            Name = "Chlorpyrifos Methyl",
                            ToxicityLevel = "II",
                            VietnameseName = "Clo-py-ri-phos methyl"
                        },
                        new
                        {
                            Id = 7,
                            CasNumber = "138261-41-3",
                            ChemicalGroup = "Thuốc trừ sâu",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Neonicotinoid, tác động hệ thần kinh côn trùng, nội hấp.",
                            IsActive = true,
                            Name = "Imidacloprid",
                            SafetyNotes = "Nguy hiểm với ong mật.",
                            ToxicityLevel = "II",
                            VietnameseName = "Imidacloprid"
                        },
                        new
                        {
                            Id = 8,
                            CasNumber = "155569-91-8",
                            ChemicalGroup = "Thuốc trừ sâu",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Trừ sâu từ lên men vi sinh, đặc trị sâu cuốn lá, sâu đục thân.",
                            IsActive = true,
                            Name = "Emamectin Benzoate",
                            ToxicityLevel = "Ib",
                            VietnameseName = "Emamectin"
                        },
                        new
                        {
                            Id = 9,
                            CasNumber = "15263-53-3",
                            ChemicalGroup = "Thuốc trừ sâu",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Dẫn xuất nereistoxin, trừ sâu tiếp xúc và vị độc.",
                            IsActive = true,
                            Name = "Cartap Hydrochloride",
                            ToxicityLevel = "II",
                            VietnameseName = "Cartap"
                        },
                        new
                        {
                            Id = 10,
                            CasNumber = "2312-35-8",
                            ChemicalGroup = "Thuốc trừ nhện",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Trừ nhện đỏ và nhện trắng trên nhiều loại cây trồng.",
                            IsActive = true,
                            Name = "Propargite",
                            ToxicityLevel = "II",
                            VietnameseName = "Propargite"
                        },
                        new
                        {
                            Id = 11,
                            CasNumber = "41814-78-2",
                            ChemicalGroup = "Thuốc trừ bệnh",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Đặc trị bệnh đạo ôn trên lúa.",
                            IsActive = true,
                            Name = "Tricyclazole",
                            ToxicityLevel = "III",
                            VietnameseName = "Tricyclazole"
                        },
                        new
                        {
                            Id = 12,
                            CasNumber = "8018-01-7",
                            ChemicalGroup = "Thuốc trừ bệnh",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Thuốc diệt nấm phổ rộng nhóm dithiocarbamate.",
                            IsActive = true,
                            Name = "Mancozeb",
                            ToxicityLevel = "III",
                            VietnameseName = "Mancozeb"
                        },
                        new
                        {
                            Id = 13,
                            CasNumber = "79983-71-4",
                            ChemicalGroup = "Thuốc trừ bệnh",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Triazole, trừ nấm phổ rộng, nội hấp.",
                            IsActive = true,
                            Name = "Hexaconazole",
                            ToxicityLevel = "III",
                            VietnameseName = "Hexaconazole"
                        },
                        new
                        {
                            Id = 14,
                            CasNumber = "6980-18-3",
                            ChemicalGroup = "Thuốc trừ bệnh",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Kháng sinh nông nghiệp từ vi khuẩn, trừ bệnh đạo ôn và bạc lá lúa.",
                            IsActive = true,
                            Name = "Kasugamycin",
                            ToxicityLevel = "III",
                            VietnameseName = "Kasugamycin"
                        },
                        new
                        {
                            Id = 15,
                            CasNumber = "119446-68-3",
                            ChemicalGroup = "Thuốc trừ bệnh",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Triazole nội hấp, trừ bệnh rỉ sắt, đốm lá phổ rộng.",
                            IsActive = true,
                            Name = "Difenoconazole",
                            ToxicityLevel = "II",
                            VietnameseName = "Difenoconazole"
                        },
                        new
                        {
                            Id = 16,
                            CasNumber = "85038-74-8",
                            ChemicalGroup = "Thuốc trừ bệnh",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Trừ bệnh bạc lá lúa do vi khuẩn Xanthomonas.",
                            IsActive = true,
                            Name = "Bismerthiazol",
                            ToxicityLevel = "III",
                            VietnameseName = "Bismerthiazol"
                        },
                        new
                        {
                            Id = 17,
                            CasNumber = "20427-59-2",
                            ChemicalGroup = "Thuốc trừ bệnh",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Thuốc trừ bệnh vô cơ, phổ rộng, tiếp xúc.",
                            IsActive = true,
                            Name = "Copper Hydroxide",
                            ToxicityLevel = "III",
                            VietnameseName = "Đồng hydroxide"
                        },
                        new
                        {
                            Id = 18,
                            CasNumber = "50512-35-1",
                            ChemicalGroup = "Thuốc trừ bệnh",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Trừ bệnh đạo ôn lúa, nội hấp mạnh.",
                            IsActive = true,
                            Name = "Isoprothiolane",
                            ToxicityLevel = "III",
                            VietnameseName = "Isoprothiolane"
                        },
                        new
                        {
                            Id = 19,
                            CasNumber = "77182-82-2",
                            ChemicalGroup = "Thuốc diệt cỏ",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Thuốc diệt cỏ không chọn lọc, tác động tiếp xúc.",
                            IsActive = true,
                            Name = "Glufosinate Ammonium",
                            ToxicityLevel = "II",
                            VietnameseName = "Glufosinate"
                        },
                        new
                        {
                            Id = 20,
                            CasNumber = "1912-24-9",
                            ChemicalGroup = "Thuốc diệt cỏ",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Thuốc diệt cỏ chọn lọc nhóm triazine, dùng cho ngô.",
                            IsActive = true,
                            Name = "Atrazine",
                            SafetyNotes = "Cần thận trọng với nguồn nước ngầm.",
                            ToxicityLevel = "III",
                            VietnameseName = "Atrazine"
                        },
                        new
                        {
                            Id = 21,
                            CasNumber = "51218-49-6",
                            ChemicalGroup = "Thuốc diệt cỏ",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Diệt cỏ chọn lọc lúa nước, dùng đầu vụ.",
                            IsActive = true,
                            Name = "Pretilachlor",
                            ToxicityLevel = "II",
                            VietnameseName = "Pretilachlor"
                        },
                        new
                        {
                            Id = 22,
                            CasNumber = "330-54-1",
                            ChemicalGroup = "Thuốc diệt cỏ",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Thuốc diệt cỏ không chọn lọc, ức chế quang hợp.",
                            IsActive = true,
                            Name = "Diuron",
                            ToxicityLevel = "III",
                            VietnameseName = "Diuron"
                        },
                        new
                        {
                            Id = 23,
                            CasNumber = "50-65-7",
                            ChemicalGroup = "Thuốc diệt ốc bươu vàng",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Diệt ốc bươu vàng trên ruộng lúa.",
                            IsActive = true,
                            Name = "Niclosamide",
                            ToxicityLevel = "II",
                            VietnameseName = "Niclosamide"
                        },
                        new
                        {
                            Id = 24,
                            CasNumber = "56073-10-0",
                            ChemicalGroup = "Thuốc diệt chuột",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Thuốc diệt chuột chống đông máu thế hệ 2, hiệu quả cao.",
                            IsActive = true,
                            Name = "Brodifacoum",
                            SafetyNotes = "Cực độc — cần bảo quản xa tầm tay trẻ em và vật nuôi.",
                            ToxicityLevel = "Ia",
                            VietnameseName = "Brodifacoum"
                        },
                        new
                        {
                            Id = 25,
                            CasNumber = "108-62-3",
                            ChemicalGroup = "Thuốc diệt ốc sên / nhớt",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Diệt ốc sên, sên nhớt trên rau màu.",
                            IsActive = true,
                            Name = "Metaldehyde",
                            ToxicityLevel = "II",
                            VietnameseName = "Metaldehyde"
                        },
                        new
                        {
                            Id = 26,
                            ChemicalGroup = "Thuốc trừ sâu sinh học",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Chiết xuất từ hạt na, trừ sâu sinh học thân thiện môi trường.",
                            IsActive = true,
                            Name = "Annonin",
                            ToxicityLevel = "III",
                            VietnameseName = "Annonin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
