http:
  routers:
    k3s-frontend:
      rule: "PathPrefix(`/`)"
      service: "k3s-service"
      entryPoints:
        - "web"
  services:
    k3s-service:
      loadBalancer:
        servers:
          - url: "http://<VM2_IP>:80"
